server:                                      # 内置tomcat
  port: 8018                                 # web访问端口号
spring:
  profiles:
    active: production
  datasource:                                # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 9511134231
    hikari:
      connection-timeout: 30000              # 等待连接池分配连接的最大时长(毫秒),超过这个时长还没可用的连接则发生SQLException，默认:30秒
      minimum-idle: 5                        # 最小连接数
      maximum-pool-size: 10                  # 最大连接数
      auto-commit: true                      # 自动提交
      idle-timeout: 600000                   # 连接超时的最大时长(毫秒),超时则被释放(retired)，默认：10分钟
      pool-name: DataSourceHikariCP          # 连接池名字
      max-lifetime: 1800000                  # 连接的生命时长(毫秒)，超时而且没被使用则被释放(retired)，默认：30分钟
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.kenrou.pojo      # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml   # mapper映射文件

mapper:
  mappers: com.kenrou.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL