server:                                      # 内置tomcat
  port: 8028                                 # web访问端口号
spring:
  datasource:                                # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: 9511134231
  data:
    elasticsearch:
      cluster-name: es6-application
      cluster-nodes: 127.0.0.1:9300
  redis:
    # Redis 单机单实例
    database: 3
    host: 127.0.0.1
    port: 6379
    password: Xxm@9511