spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: 9511134231
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
