spring:
  datasource:
    url: jdbc:mysql://172.19.190.238:3306/foodie-shop-dev?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    password: Xxm@9511
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password: Xxm@9511